version: '2'
services:
  mgcard-app:
    image: mgcard
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mgcard-postgresql:5432/MGCARD
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mgcard-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mgcard-elasticsearch:9200
    ports:
      - 8443:8443
  mgcard-postgresql:
    extends:
      file: postgresql.yml
      service: mgcard-postgresql
  mgcard-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mgcard-elasticsearch
